apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rampart.fullname" . }}-config
  labels:
    {{- include "rampart.labels" . | nindent 4 }}
data:
  BIND_ADDR: {{ .Values.config.bindAddr | quote }}
  RUST_LOG: {{ .Values.config.rustLog | quote }}
