apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rampart.fullname" . }}
  labels:
    {{- include "rampart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "rampart.databaseUrl" . | quote }}
  SESSION_KEY: {{ include "rampart.sessionKey" . | quote }}
{{- if .Values.postgres.embedded }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rampart.postgres.fullname" . }}
  labels:
    {{- include "rampart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_PASSWORD: {{ include "rampart.postgresPassword" . | quote }}
{{- end }}
