[package]
name         = "rampart-notifier"
version      = "0.1.0"
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }

[dependencies]
rampart-core = { path = "../rampart-core" }
rampart-db   = { path = "../rampart-db" }

tokio       = { workspace = true }
async-trait = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
reqwest     = { workspace = true }
lettre      = { workspace = true }
tracing     = { workspace = true }
thiserror   = { workspace = true }
anyhow      = { workspace = true }
time        = { workspace = true }
uuid        = { workspace = true }
liquid      = { workspace = true }
once_cell   = { workspace = true }
hmac        = { workspace = true }
sha2        = { workspace = true }
sha1        = { workspace = true }
base64      = { workspace = true }
rand        = { workspace = true }
hex         = { workspace = true }
urlencoding  = { workspace = true }
jsonwebtoken = { workspace = true }

[dev-dependencies]
rampart-core = { path = "../rampart-core", features = ["testing"] }
