[package]
name         = "rampart-scheduler"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }

[dependencies]
rampart-core     = { path = "../rampart-core" }
rampart-db       = { path = "../rampart-db" }
rampart-checker  = { path = "../rampart-checker" }
rampart-notifier = { path = "../rampart-notifier" }

tokio       = { workspace = true }
reqwest     = { workspace = true }
futures     = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
tracing     = { workspace = true }
time        = { workspace = true }
uuid        = { workspace = true }
async-trait = { workspace = true }
hmac        = { workspace = true }
sha2        = { workspace = true }
hex         = { workspace = true }
